services:
  keycloak:
      build:
          context: .
          dockerfile: Dockerfile
          args:
              - KEYCLOAK_IMAGE=${KEYCLOAK_IMAGE}
      environment:
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin
          DB_VENDOR: h2
          DEBUG: 'true'        # Debug mode on/off
          # DEBUG_SUSPEND='n'   # Wait for debugger connection at startup; useful when stepping through startup code
          DEBUG_PORT: '*:5005'
      volumes:
          - ./h2:/opt/keycloak/data/h2
      ports:
          - 8080:8080
          - 9000:9000
          - 5005:5005
  example-app:
      build:
        context: ./example
      env_file:
        - ./example/.env
      volumes:
        - type: bind
          source: example/src
          target: /app
      ports:
        - 8000:8000
