services:
  echo_server:
    image: jmalloc/echo-server
    environment:
      LOG_HTTP_BODY: 1
      LOG_HTTP_HEADERS: 1
    ports:
      - 80:8080

  keycloak:
      build:
          context: .
          dockerfile: Dockerfile
          args:
              - KEYCLOAK_IMAGE=${KEYCLOAK_IMAGE}
      environment:
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin
          DB_VENDOR: h2
          DEBUG: 'true'        # Debug mode on/off
          # DEBUG_SUSPEND='n'   # Wait for debugger connection at startup; useful when stepping through startup code
          DEBUG_PORT: '*:5005'
      volumes:
          - ./h2:/opt/keycloak/data/h2
      ports:
          - 8024:8080
          - 9000:9000
          - 5005:5005
