name: Release

on:
  push:
    tags:
      - v**

jobs:
  build:
    uses: ./.github/workflows/build.yml
  release:
    needs: build
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v5
        with:
          name: packages
          path: staging
      - name: "Create release"
        run: gh release create ${GITHUB_REF_NAME} staging/* --generate-notes --verify-tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}